---
-    name: Enable ufw
     ufw:
         state: enabled
         policy: allow

-    name: Allow OpenSSH 22port
     ufw:
         rule: allow
         name: OpenSSH

-    name: Allow 80 port tcp
     ufw:
         rule: allow
         port: '80'
         proto: tcp

-    name: Insert a rule on line 1
     ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 3000
        jump: DROP
        action: insert
        rule_num: 1
