---
-    name: Pull an image of grafana
     community.docker.docker_image:
         name: grafana/grafana
         source: pull
         pull:
             platform: amd64

-    name: Start a container grafana with a command
     community.docker.docker_container:
         name: my_grafana
         image: grafana/grafana
         ports:
             - "3000:3000"
         command: ["sleep", "infinity"]

-    name: Pull an image of nginx
     community.docker.docker_image:
         name: nginx
         source: pull
         pull:
             platform: amd64
         volumes:  
             - ./tasks/grafana:/etc/nginx/sites-available
         
-    name: Start a container nginx with a command
     community.docker.docker_container:
         name: my_nginx
         image: nginx
         ports:
             - "80:80"

#-    name: Add a container to a network, leaving existing containers connected
#     docker_network:
#         name: network_one
#         connected:
#             - sleepy
#             - sleepytwo
#         appends: yes
   



